spring.application.name=auth-service

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/orynx
spring.datasource.username=postgres
spring.datasource.password=1947

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=*

# Logging
logging.level.org.springframework.kafka=DEBUG

#Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=orynx-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.consumer.properties.spring.json.value.default.type=com.orynx.auth.user.event.UserRegisteredEvent

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

#JWT
# JWT
jwt.secret=orynxSecretKeyOrynxSecretKey123456789
jwt.expiration=3600000