spring.application.name=execution-service

server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/orynx
spring.datasource.username=postgres
spring.datasource.password=1947

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=*

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=execution-service
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.value.default.type=com.orynx.execution.workflow.event.WorkflowExecutionRequestEvent

spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.consumer.properties.spring.json.trusted.packages=*