spring.application.name=orchestrator-service

server.port=8082

##################################################
# Planning Service
##################################################

planning.service.url=http://localhost:8083
planning.service.connect-timeout=5000
planning.service.read-timeout=10000

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/orynx
spring.datasource.username=postgres
spring.datasource.password=1947

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka
spring.kafka.bootstrap-servers=localhost:29092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=true

spring.kafka.consumer.group-id=orynx-orchestrator-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Actuator
management.endpoints.web.exposure.include=*

# Logging
logging.level.org.springframework.kafka=INFO

#Nvidia
nvidia.api.url=https://integrate.api.nvidia.com/v1/chat/completions

nvidia.api.key=${NVIDIA_API_KEY}

##################################################
# Resilience4j
##################################################

resilience4j.circuitbreaker.instances.planningService.register-health-indicator=true
resilience4j.circuitbreaker.instances.planningService.sliding-window-size=10
resilience4j.circuitbreaker.instances.planningService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.planningService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.planningService.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.planningService.permitted-number-of-calls-in-half-open-state=3

##################################################
# Retry
##################################################

resilience4j.retry.instances.planningService.max-attempts=3
resilience4j.retry.instances.planningService.wait-duration=2s
resilience4j.retry.instances.planningService.enable-exponential-backoff=true
resilience4j.retry.instances.planningService.exponential-backoff-multiplier=2

